version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sass
    versions:
    - "> 1.26.8, < 1.27"
  - dependency-name: sass-loader
    versions:
    - ">= 10.0.a, < 10.1"
  - dependency-name: ts-jest
    versions:
    - "> 26.3.0, < 26.4"
  - dependency-name: typescript
    versions:
    - "> 3.9.5, < 4"
  - dependency-name: "@types/jest"
    versions:
    - "> 25.2.3, < 26"
  - dependency-name: "@types/jest"
    versions:
    - "> 26.0.8, < 26.1"
  - dependency-name: vue
    versions:
    - "> 2.6.12, < 2.7"
  - dependency-name: vue-class-component
    versions:
    - "> 7.2.3, < 7.3"
  - dependency-name: "@vue/cli-plugin-e2e-cypress"
    versions:
    - ">= 4.4.a, < 4.5"
  - dependency-name: "@vue/cli-plugin-e2e-cypress"
    versions:
    - "> 4.5.0, < 4.6"
  - dependency-name: "@vue/cli-plugin-pwa"
    versions:
    - "> 4.4.1, < 4.5"
  - dependency-name: "@vue/cli-plugin-pwa"
    versions:
    - "> 4.5.0, < 4.6"
  - dependency-name: "@vue/cli-plugin-typescript"
    versions:
    - "> 4.5.4, < 4.6"
  - dependency-name: "@vue/cli-plugin-unit-jest"
    versions:
    - "> 4.4.1, < 4.5"
  - dependency-name: "@vue/cli-plugin-unit-jest"
    versions:
    - "> 4.5.0, < 4.6"
  - dependency-name: vue-property-decorator
    versions:
    - "> 8.4.2, < 9"
  - dependency-name: vue-router
    versions:
    - ">= 3.4.a, < 3.5"
  - dependency-name: vue-template-compiler
    versions:
    - "> 2.6.12, < 2.7"
  - dependency-name: "@vue/test-utils"
    versions:
    - "> 1.0.5, < 1.1"
  - dependency-name: vuetify
    versions:
    - "> 2.3.10, < 2.4"
  - dependency-name: vuetify-loader
    versions:
    - "> 1.4.4, < 2"
  - dependency-name: vuex
    versions:
    - "> 3.4.0, < 4"
  - dependency-name: websocket-extensions
    versions:
    - "> 0.1.4, < 0.2"
  - dependency-name: ts-jest
    versions:
    - 26.4.4
    - 26.5.0
    - 26.5.2
    - 26.5.3
  - dependency-name: core-js
    versions:
    - 3.8.1
    - 3.8.3
    - 3.9.1
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
    - 4.5.9
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.11
    - 4.5.9
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.2.2
  - dependency-name: sass-loader
    versions:
    - 10.1.0
    - 10.1.1
  - dependency-name: sass
    versions:
    - 1.32.0
    - 1.32.5
  - dependency-name: "@vue/test-utils"
    versions:
    - 1.1.2
